{% set name = "msrest" %}
{% set version = "0.6.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8f5b47e90e0a78a3345784da854352fa1a8a890d4ec60a87371c9f9850ec3f42

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - certifi >=2017.4.17
    - isodate >=0.6.0
    - python
    - requests >=2.16
    - requests-oauthlib >=0.5.0

test:
  imports:
    - msrest
    - msrest.authentication
    - msrest.exceptions
    - msrest.pipeline
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/msrest-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: AutoRest swagger generator Python client runtime.

extra:
  recipe-maintainers:
    - marcelotrevisani
