{% set name = "msrest" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 2210a4dff54c6d3af30bf2fc10db206a1bc5b097c654ce54b0ecd633d762afdf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - certifi >=2017.4.17
    - isodate >=0.6.0
    - python
    - requests >=2.16
    - requests-oauthlib >=0.5.0

test:
  imports:
    - msrest
    - msrest.authentication
    - msrest.exceptions
    - msrest.pipeline
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/msrest-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: AutoRest swagger generator Python client runtime.

extra:
  recipe-maintainers:
    - xylar
    - marcelotrevisani
