{% set name = "msrest" %}
{% set version = "0.6.7" %}
{% set sha256 = "05538c68251eb0c81bd2010524d8ff36d4266ec0669338fbdcecfd23c733231c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - requests >=2.14
    - requests-oauthlib >=0.5.0
    - isodate >=0.6.0
    - certifi >=2017.4.17
test:
  imports:
    - msrest
    - msrest.authentication
    - msrest.exceptions
    - msrest.pipeline

about:
  home: https://github.com/Azure/msrest-for-python
  license: MIT
  license_family: MIT
  summary: AutoRest swagger generator Python client runtime.
  
extra:
  recipe-maintainers:
    - ivoflipse
