travis:
  secure:
    BINSTAR_TOKEN: DEVrwx9/pVaZzx5BAppxKK2p3KfycFVnYP71l+GxXdn0NuEO3Wj2y3pIGuGpPPPgElBzkL5QLFAZDL6BrXSLmHL5H3V+l6YhfPVPI10jCpZ6Npy90snnqgfiuPqhWuHaCDPusWtvBXFdz4f2H5i1HA+YSiy5eJGL+d8hUTj9ZqNvpRl5XryPJ9ZnCI7Z8SZe0d7xATSoiq6QGSijYEEOPjA/a9BrH1dTtHlP2wT+kH7s51qwgusQa4v8Xf/A0veJzlhG9NdhFEp1ENINTSrF6wi0DVDeS4nRwOsu5QpoNmZ/rRbKgXPF4yp9+u9f2U+bLcOrpFvE5g94n928Y9nKpoGU3aQ1w8f+j9kiyWmd9HFHOeyGiZqYlLWVWAS91ZmL6yYpXXTQT7Vj18z8SvXoKvOSdRvQpfDNCizve9/z0RkDhrNr9OonvjJ3TFeatU8W+ljB6YTaLLtEilC+bQK1PxH/EKOzcbb1RhFlkXGU5tdazFCDGsgVL41quct95Nbta96psWq2tFd+EfTyJY5IK4DCfSD08WoIKATPINyLUWv2eT7uF5Px6727mjE/Xtp7YoJWqTLKoP2XKoKpyMZsrmkpEssJGMeKOZTnoyt0zVScgimBDy+SPnEQ4f9ltZK1tPz+X8LqkngWAusUKEDQgo6SynIPJOf1yxkTgke1ayU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
