travis:
  secure:
    BINSTAR_TOKEN: MuzOpHUqUj0K8jHibvMTKw1Mw8rUM9BN3YqUtExwQu6W5dTujuGrAyzM3SbJQ3uMtivmXRTrQyqoE+DpucUiI0viyh7rQam5X7T2N23PJnIaRUJ1h5Uf3xskjkMlK8XvtWpgxgKRAVhts8qNoLUvha49XkN1Al4keAFRRIMVfoJys/1N3dAoUrENm+O0bElJsv+j174M5XlTXOHBeOuAi67CdTOD+D71fASFG/rFL4CH3xMwcF0rv2PieGSCZgHTfSCudzhmWicriOm3QZ8TyEt2p4LofdO7KasTXQsjmzBHsfpfzaHcDhgUMD/mD48AeBrUAg/ICZxBrgGLxgQLxMQBKX3Ki1GVRtVtrbV8n5ltA3ko5gxO0NxOVee6qwNmmLDyrBXGaAIU5hi/UtimozEFc2Al7ajanDFjUoWizaBDpynD2HrSjhMZvjVtLam4ZZG5ZnOmLd8mRHzzgy4Dhbj/n9ufCgIZrqIFCcU1FoMD2AQJiTt+OBDuhgyG4dsWoUeDF4CzQuXEwp5p2c191MGtdM4a6nFMETi3ZAmHCEFzl3fywvE+Z4pWyYU9uRttyoURsgmUYu247KcXswRq0LyeFtI3dTCtABuKUiyVIJg2MuN3kW8f6OZtK3UmY4rhpSQxRNT9qsp5qnDOQEQ+iJfNIT70FNdvo5nc+RrFKwc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
